name = "ParameterEstimateScatterPlots"
uuid = "d240946c-85f5-49b8-b3a9-994f826016ae"
authors = ["Steven Whitaker <stwhit@umich.edu>"]
version = "0.1.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
RecipesBase = "1.1"
julia = "1.6"
